name: Libraray Generate Release

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # JDK 설정
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          check-latest: true

      # Release Note 정보 가져오기
      - name: Get Release Info
        id: release
        run: |
          echo ::set-output name=version::$(grep Version: release_note.txt | awk '{print $2}')
          echo ::set-output name=title::$(grep Title: release_note.txt | awk '{print $2}')

      # Release Version 명 가져오기
      - name: Get Version Name
        id: versionName
        run: echo ::set-output name=val::${{steps.release.outputs.version}}

      # Release Title 가져오기
      - name: Get Release Title Name
        id: releaseTitle
        run: echo ::set-output name=val::${{steps.release.outputs.title}}

      # Release Message 가져오기
      - name: Get Release Message
        id: releaseMessage
        run: |
          RELEASE_BODY=$(sed -n '3,$p' release_note.txt | less)
          RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
          RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
          RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"
          echo ::set-output name=val::${RELEASE_BODY}

      # 릴리즈 생성
      # release_name: 릴리즈 제목
      # tag_name: 버전 이름
      # body: 릴리즈 메시지 내용
      - name: Generate Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{steps.releaseTitle.outputs.val}}
          tag_name: ${{steps.versionName.outputs.val}}
          body: |
            ${{steps.releaseMessage.outputs.val}}
          draft: false
          prerelease: false

      # Android SDK 설정
      # - name: SetUp Android SDK
      #  uses: android-actions/setup-android@v2

      # gradlew 권한 획득
      # - name: Grant execute permission for gradlew
      #  run: chmod +x gradlew

      # 릴리즈 노트 작성
      # - name: Generate Release Note
      #   run: |
      #    ./gradlew generateReleaseNote --stacktrace
